version: "3.7"
services:
  #outro container --- backend
  springweb:
    container_name: grape_container
    build: . #preciso do Dockerfile para gerar a imagem
    image: "tizuey/grape"
    ports:
      - "8081:8080"
    networks:
      - servers
    depends_on:
      - mysql_db
    environment:
      - SPRING_PROFILES_ACTIVE=docker



networks:
  servers:
    driver: bridge


